amsapp/urls.py
from django.urls import path,include
from .views import *

app_name = 'amsapp'

urlpatterns = [
    path('',ArtistListView.as_view(),name="artist_list"),
    path('artists/add/',ArtistAddView.as_view(),name="artist_add"),
    path('artist/<int:id>/update/',ArtistUpdateView.as_view(),name="artist_update"),
    path('artist/<int:id>/delete/',ArtistDeleteView.as_view(),name="artist_delete"),

    path('musics/<int:id>/',MusicListView.as_view(),name="music_list"),
    path('musics/add/<int:id>/',MusicAddView.as_view(),name="music_add"),
    path('music/<int:id>/update/',MusicUpdateView.as_view(),name="music_update"),
    path('music/<int:id>/delete/',MusicDeleteView.as_view(),name="music_delete"),   

    path('users/',UserListView.as_view(),name="user_list"),
    path('users/add/',UserAddView.as_view(),name="user_add"),
    path('user/<int:id>/update/',UserUpdateView.as_view(),name="user_update"),
    path('user/<int:id>/delete/',UserDeleteView.as_view(),name="user_delete"),   

    path('login/',ArtistLoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),

    path('export/',ArtitsFileExportView.as_view(),name="export"),
    path('import/',ArtitsFileImportView.as_view(),name="import"),

    
    
]

api/urls.py
from django.urls import path
from .views import *

urlpatterns =[
    path("login/", LoginAPIView.as_view(), name="loginapi"),
    path('get-access/<int:id>/',GetAccessAPIView.as_view(), name="get_access"),

    path('artist/post/',ArtistPostAPIView.as_view(),name="artist_post"),
    path('artist/<int:id>/update/',ArtistUpdateAPIView.as_view(),name="artist_update"),
    path('artist/<int:id>/delete/',ArtistDeleteAPIView.as_view(),name="artist_delete"),
    path('artists/',ArtistListAPIView.as_view(),name="artist_list"),

    path('music/post/',MusicPostAPIView.as_view(),name="music_post"),
    path('music/<int:id>/update/',MusicUpdateAPIView.as_view(),name="music_update"),
    path('music/<int:id>/delete/',MusicDeleteAPIView.as_view(),name="music_delete"),
    path('musics/<int:id>/',MusicListAPIView.as_view(),name="music_list"),

    path('user/post/',UserPostAPIView.as_view(),name="user_post"),
    path('user/<int:id>/update/',UserUpdateAPIView.as_view(),name="user_update"),
    path('user/<int:id>/delete/',UserDeleteAPIView.as_view(),name="user_delete"),
    path('users/',UserListAPIView.as_view(),name="user_list"),

    path('artist-exp/',CSVExportArtistAPIView.as_view(), name="artist_export"),
    path('artist-imp/',CSVImportArtistAPIView.as_view(), name="artist_import"),

]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('amsapp.urls')),
    path("api/",include('api.urls')),
    path("frontend/",include('artistapp.urls')),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/music/music_add.html
{% extends '../basepage.html' %}
{% load static %}
{% block title %}
    Music Form
{% endblock title %}

{% block main %}
    <section>
      {% if msg_error %}
      <div class="alert alert-warning alert-dismissible fade show  mt-2 mb-2" role="alert">
         {{msg_error}}
      </div>
      {% endif %}
        <h4 class="text-center m-3">Music Form</h4>
        <form method="POST" class="border rounded border-secondary p-3">
            {% csrf_token %}
            <div class="form-group">
              <label for="formGroupExampleInput">Song Title</label>
              {{forms.title}}
              {{forms.title.errors}}
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Album Name</label>
              {{forms.album_name}}
              {{forms.album_name.errors}}
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Genre</label>
                {{forms.genre}}
                {{forms.genre.errors}}
                
            </div>

            <button type="submit" name="music_btn" class="form-control btn-info">Save</button>

          </form>
    </section>

{% endblock main %}

templates/music/music_delete.html
{% extends '../basepage.html' %}
{% load static %}
{% block title %}
    Music delete
{% endblock title %}

{% block main %}


    <section>
        <div class="border border-secondary rounded p-3 mt-5"
            <h5 class="text-center m-3 text-danger">Are you sure, you want delete the music '<span class="text-info">{{obj.title}}</span>'?</h5>
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="artist_id" value="{{obj.artist_id}}">
                <button type="submit" name="music_name" class="btn btn-danger mt-2">Delete</button>
            </form>
        </div>
    </section>

{% endblock main %}

templates/music/music_list.html
{% extends '../basepage.html' %}
{% load static %}
{% block title %}
    Music List
{% endblock title %}

{% block main %}


    <section>
        <h4 class="text-center m-3">Music Lists
          {% if artist_id %}
        <a href="{% url 'amsapp:music_add' artist_id %}" class="btn btn-info float-right btn-sm">Add New Music</a></h4>
         {% endif %}
        <h5 class="m-2">Singer : {{singer}}</h5>
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">S.N.</th>
                <th scope="col">Song Title</th>
                <th scope="col">Album Name</th>
                <th scope="col">Genre</th>
                <th scope="col">Created</th>
                <th scope="col">Updated</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for music in musics %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ music.title|truncatechars:25 }}</td>
                  <td>{{ music.album_name }}</td>
                  <td>{{ music.genre|default_if_none:'--' }}</td>
                  <td>{{ music.created_at}}</td>
                  <td>{{ music.updated_at }}</td>
                  <td>
                    <a href="{% url 'amsapp:music_update' music.id %}" class="btn btn-info btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <a href="{% url 'amsapp:music_delete' music.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></a>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="6">
                    No songs
                  </td>
                </tr>
                
                {% endfor %}
            </tbody>
          </table>
          {% if pages %}
          <nav aria-label="...">
            <ul class="pagination">
              {% if previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{previous}}" tabindex="-1">Previous</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="" tabindex="-1">Previous</a>
              </li>
              {% endif %}

              {% for page in pages %}
              {% if page == current_page %}
              <li class="page-item active">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              {% endfor %}
              {% if next_page %}
              <li class="page-item">
                <a class="page-link" href="?page={{next_page}}" >Next </a>
              </li>
                {% else %}
              <li class="page-item disabled">
                <a class="page-link " href="">Next</a>
              </li>
                {% endif %}

            </ul>
          </nav>
          {% endif %}
    </section>

{% endblock main %}