api/urls.py
from django.urls import path
from .views import *

urlpatterns =[
    path("login/", LoginAPIView.as_view(), name="loginapi"),
    path('get-access/<int:id>/',GetAccessAPIView.as_view(), name="get_access"),

    path('artist/post/',ArtistPostAPIView.as_view(),name="artist_post"),
    path('artist/<int:id>/update/',ArtistUpdateAPIView.as_view(),name="artist_update"),
    path('artist/<int:id>/delete/',ArtistDeleteAPIView.as_view(),name="artist_delete"),
    path('artists/',ArtistListAPIView.as_view(),name="artist_list"),

    path('music/post/',MusicPostAPIView.as_view(),name="music_post"),
    path('music/<int:id>/update/',MusicUpdateAPIView.as_view(),name="music_update"),
    path('music/<int:id>/delete/',MusicDeleteAPIView.as_view(),name="music_delete"),
    path('musics/<int:id>/',MusicListAPIView.as_view(),name="music_list"),

    path('user/post/',UserPostAPIView.as_view(),name="user_post"),
    path('user/<int:id>/update/',UserUpdateAPIView.as_view(),name="user_update"),
    path('user/<int:id>/delete/',UserDeleteAPIView.as_view(),name="user_delete"),
    path('users/',UserListAPIView.as_view(),name="user_list"),

    path('artist-exp/',CSVExportArtistAPIView.as_view(), name="artist_export"),
    path('artist-imp/',CSVImportArtistAPIView.as_view(), name="artist_import"),

]

artistapp/urls.py
from django.urls import path
from .views import *

app_name = 'artistapp'

urlpatterns =[
    path('',ArtistListView.as_view(),name="a_artist_list"),
    path('artist/add/',ArtistAddView.as_view(),name="a_artist_add"),
    path('artist/<int:id>/update/',ArtistUpdateView.as_view(),name="a_artist_update"),
    path('artist/<int:id>/delete/',ArtistDeleteView.as_view(),name="a_artist_delete"),

    path('musics/<int:id>/',MusicListView.as_view(),name="a_music_list"),
    path('music/add/<int:id>/',MusicAddView.as_view(),name="a_music_add"),
    path('music/<int:id>/update/',MusicUpdateView.as_view(),name="a_music_update"),
    path('music/<int:id>/delete/',MusicDeleteView.as_view(),name="a_music_delete"),

    path('users/',UserListView.as_view(),name="a_user_list"),
    path('user/add/',UserAddView.as_view(),name="a_user_add"),
    path('user/<int:id>/update/',UserUpdateView.as_view(),name="a_user_update"),
    path('user/<int:id>/delete/',UserDeleteView.as_view(),name="a_user_delete"),

    path('login/',ArtistLoginView.as_view(),name="a_login"),
    path('logout/',LogoutView.as_view(),name="a_logout"),

    path('csv-artist-export/',CSVExportArtistView.as_view(),name="csv_artist"),
    path('csv-artist-import/',CSVImportArtistView.as_view(),name="csv_artist_import"),
]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('amsapp.urls')),
    path("api/",include('api.urls')),
    path("frontend/",include('artistapp.urls')),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/normal/artist_add.html
{% extends 'normal/basepage.html' %}
{% load static %}
{% block title %}
    Artist Form
{% endblock title %}

{% block main %}
    <section>
        <h4 class="text-center m-3">Artist Form
        <a href="{% url 'artistapp:csv_artist_import' %}" class="btn btn-info btn-sm float-right m-2">Upload CSV Files</a>
        </h4>
        <form method="POST" class="border rounded border-secondary p-3">
            {% csrf_token %}
            <div class="form-group">
              <label for="formGroupExampleInput">Name</label>
              {{forms.name}}
              {{forms.name.errors}}
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">D.O.B.</label>
              {{forms.dob}}
              {{forms.dob.errors}}
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Gender</label>
                {{forms.gender}}
                {{forms.gender.errors}}
                
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">First Album Release Date</label>
                {{forms.first_release_year}}
                {{forms.first_release_year.errors}}
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Total Release Album</label>
                {{forms.no_of_albums_released}}
                {{forms.no_of_albums_released.errors}}
            </div>
            <button type="submit" name="artist_btn" class="form-control btn-primary">Save</button>

          </form>
    </section>

{% endblock main %}

templates/normal/artist_delete.html
{% extends 'normal/basepage.html' %}
{% load static %}
{% block title %}
    Artist delete
{% endblock title %}

{% block main %}


    <section>
        <div class="border border-secondary rounded p-3 mt-5"
            <h5 class="text-center m-3 text-danger">Are you sure, you want delete the artist '<span class="text-info">{{artist.name}}</span>'?</h5>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" name="artist_name" class="btn btn-danger mt-2">Delete</button>
            </form>
        </div>
    </section>

{% endblock main %}

templates/normal/artist_list.html
{% extends 'normal/basepage.html' %}
{% load static %}
{% block title %}
    Artist List
{% endblock title %}

{% block main %}


    <section>
        <h4 class="text-center m-3">Artist Lists
          <a href="{% url 'artistapp:a_artist_add' %}" class="btn btn-info btn-sm float-right m-2">Add New Artist</a>
          <a href="{% url 'artistapp:csv_artist' %}" class="btn btn-primary btn-sm float-right m-2">Export Artist List</a></h4>
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">S.N.</th>
                <th scope="col" >Artist Name</th>
                <th scope="col">DOB</th>
                <th scope="col">Gender</th>
                <th scope="col">First Date of Release</th>
                <th scope="col">Number of Album</th>
                <th scope="col">Created</th>
                <th scope="col">Updated</th>
                <th scope="col" width="170">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for artist in artist_lists %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ artist.name|truncatechars:25 }}</td>
                  <td>{{ artist.dob|date:'d M Y'|default_if_none:'--' }}</td>
                  <td>{% if artist.gender == 'm' %} Male{% elif artist.gender == 'f' %} Female {% else %} Others{% endif %}</td>
                  <td>{{ artist.first_release_year|default_if_none:'--' }}</td>
                  <td>{{ artist.no_of_albums_released|default_if_none:'--' }}</td>
                  <td>{{ artist.created_at|date:'d M Y'}}</td>
                  <td>{{ artist.updated_at|date:'d M Y' }}</td>
                  <td>
                    <a href="{% url 'artistapp:a_music_list' artist.id %}" class="btn btn-info btn-sm"><i class="fa fa-solid fa-eye"></i></a>
                    <a href="{% url 'artistapp:a_artist_update' artist.id %}" class="btn btn-info btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <a href="{% url 'artistapp:a_artist_delete' artist.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          <nav aria-label="...">
            <ul class="pagination">
              {% if artist_lists.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{artist_lists.previous_page_number}}" tabindex="-1">Previous</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="" tabindex="-1">Previous</a>
              </li>
              {% endif %}

              {% for page in totalpagelist %}
              {% if page == current_page %}
              <li class="page-item active">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              {% endfor %}
              {% if artist_lists.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{artist_lists.next_page_number}}" >Next</a>
              </li>
                {% else %}
              <li class="page-item disabled">
                <a class="page-link " href="">Next</a>
              </li>
                {% endif %}

            </ul>
          </nav>
    </section>

{% endblock main %}

templates/normal/artist_upload_csv.html
{% extends 'normal/basepage.html' %}
{% load static %}
{% block title %}
    Artist CSV File upload
{% endblock title %}

{% block main %}


    <section>
        <h4 class="text-center m-3">Upload File</h4>
            <div class="col-sm-12">
                <form method="POST" enctype="multipart/form-data" class="border border-secondary rounded p-4">
                    {% csrf_token %}
                    {{form.file_name}}
                    <button type="submit" class="btn btn-secondary m-3">Upload</button>
                </form>
            </div>
    </section>

{% endblock main %}

templates/normal/basepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <title>
       {% block title %}{% endblock title %} | Artist Management System
    </title>
    <style>
        #footer {
            position: fixed;
            padding: 10px 10px 0px 10px;
            bottom: 0;
            width: 100%;
            /* Height of the footer*/
            height: 40px;
            background: grey;
        }
        .m-height-600 {
            min-height: 600px;
          }
    </style>
</head>
<body>
    <div class="m-0 p-0">
        <div class="container">
            <div class="m-3">
                <h2>ARTIST MANAGEMENT SYSTEM</h2>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <div class="container">
            <a class="navbar-brand font-weight-bold" href="#">Dashboard</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse bg-info" id="navbarNavDropdown">
                {% if request.user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                    
                    <li class="nav-item">
                    <a class="nav-link  text-light" href="{% url 'artistapp:a_artist_list' %}">Artists</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link  text-light" href="{% url 'artistapp:a_user_list' %}">Users</a>
                    </li>
                
                
                </ul>
                {% endif %}
                <span class="navbar-text">
                    {% if request.user.is_authenticated %}
                    <span class="text-dark">Welcome {{request.user.first_name}} {{request.user.last_name}} | </span>
                    <a href="{% url 'artistapp:a_logout' %}" class="text-light">Logout</a>
                    {% else %}
                    <a href="{% url 'artistapp:a_login' %}" class="text-light">Login</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="page-content">
            <div class="container-fluid">
                <div class="m-height-600">
                {% block main %}

                {% endblock main %}
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <hr>
            <p>Artist Management System, by Pravin Rai, 2023</p>
        </div>
    </footer>
`   <script src="{% static 'js/bootstrap.min.js' %}">
    
</script>
</body>
</html>

templates/normal/login copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Login | Artist Management System</title>
</head>
<body>
    
    <div class="container">
    <main>
        <div class="account-pages my-5 pt-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card overflow-hidden">
                            <div class="bg-soft-primary">
                                <div class="row">
                                    <div class="col-7">
                                        <div class="text-primary p-4">
                                            <h5 class="text-primary">ARTIST MAMAGEMENT SYSTEM</h5>
                                            <p>Sign in to continue to AMS</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body pt-0"> 
                               
                                <div class="p-2">
                                    <form class="form-horizontal" action="" method="POST">
                                        {% csrf_token %}
        
                                        <div class="form-group">
                                            <label for="username">Username</label>
                                            <input type="text" class="form-control" id="username" name="email" placeholder="Enter email">
                                        </div>
                
                                        <div class="form-group">
                                            <label for="userpassword">Password</label>
                                            <input type="password" name="password" class="form-control" id="userpassword" placeholder="Enter password">
                                        </div>
                
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="customControlInline">
                                            <label class="custom-control-label" for="customControlInline">Remember me</label>
                                        </div>
                                        
                                        <div class="mt-3">
                                            <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">Log In</button>
                                        </div>
            
                                       

                                        <div class="mt-4 text-center">
                                            <h5 class="font-size-14 mb-3">Sign in with</h5>
            
                                            <ul class="list-inline">
                                                <li class="list-inline-item">
                                                    <a href="javascript::void()" class="social-list-item bg-primary text-white border-primary">
                                                        <i class="mdi mdi-facebook"></i>
                                                    </a>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a href="javascript::void()" class="social-list-item bg-info text-white border-info">
                                                        <i class="mdi mdi-twitter"></i>
                                                    </a>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a href="javascript::void()" class="social-list-item bg-danger text-white border-danger">
                                                        <i class="mdi mdi-google"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>

                                        <div class="mt-4 text-center">
                                            <a href="auth-recoverpw.html" class="text-muted"><i class="mdi mdi-lock mr-1"></i> Forgot your password?</a>
                                        </div>
                                    </form>
                                </div>
            
                            </div>
                        </div>
                        <div class="mt-5 text-center">
                            
                            <div>
                                <p>Don't have an account ? <a href="auth-register.html" class="font-weight-medium text-primary"> Signup now </a> </p>
                                <p>© <script>document.write(new Date().getFullYear())</script> Artist Management System, by Pravin Rai</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
          </main>
    </div>
   
`   <script src="{% static 'js/bootstrap.min.js' %}">
    
</script>
</body>
</html>

templates/normal/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Login | Artist Management System</title>
</head>
<body>
    
    <div class="container">
    <main>
        <div class="account-pages my-5 pt-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card overflow-hidden">
                            <div class="bg-soft-primary">
                                <div class="row">
                                    <div class="col-7">
                                        <div class="text-primary p-4">
                                            <h5 class="text-primary">ARTIST MAMAGEMENT SYSTEM</h5>
                                            <p>Sign in to continue to AMS</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body pt-0"> 
                               
                                <div class="p-2">
                                    <form class="form-horizontal" action="" method="POST">
                                        {% csrf_token %}
        
                                        <div class="form-group">
                                            <label for="username">Username</label>
                                            <input type="text" class="form-control" id="username" name="email" placeholder="Enter email">
                                        </div>
                
                                        <div class="form-group">
                                            <label for="userpassword">Password</label>
                                            <input type="password" name="password" class="form-control" id="userpassword" placeholder="Enter password">
                                        </div>
                
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="customControlInline">
                                            <label class="custom-control-label" for="customControlInline">Remember me</label>
                                        </div>
                                        
                                        <div class="mt-3">
                                            <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">Log In</button>
                                        </div>
            
                                       

                                        <div class="mt-4 text-center">
                                            <h5 class="font-size-14 mb-3">Sign in with</h5>
            
                                            <ul class="list-inline">
                                                <li class="list-inline-item">
                                                    <a href="javascript::void()" class="social-list-item bg-primary text-white border-primary">
                                                        <i class="mdi mdi-facebook"></i>
                                                    </a>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a href="javascript::void()" class="social-list-item bg-info text-white border-info">
                                                        <i class="mdi mdi-twitter"></i>
                                                    </a>
                                                </li>
                                                <li class="list-inline-item">
                                                    <a href="javascript::void()" class="social-list-item bg-danger text-white border-danger">
                                                        <i class="mdi mdi-google"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>

                                        <div class="mt-4 text-center">
                                            <p>Don't have an account ? <a href="{% url 'artistapp:a_user_add' %}" class="font-weight-medium text-primary"> Signup now </a> </p>
                                        </div>
                                    </form>
                                </div>
            
                            </div>
                        </div>
                        <div class="mt-5 text-center">
                            
                            <div>
                                <p>© <script>document.write(new Date().getFullYear())</script> Artist Management System, by Pravin Rai</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
          </main>
    </div>
   
`   <script src="{% static 'js/bootstrap.min.js' %}">
    
</script>
</body>
</html>

templates/normal/music_delete.html
{% extends 'normal/basepage.html' %}
{% load static %}
{% block title %}
    Song delete
{% endblock title %}

{% block main %}


    <section>
        <div class="border border-secondary rounded p-3 mt-5"
            <h5 class="text-center m-3 text-danger">Are you sure, you want delete the song titled '<span class="text-info">{{music.title}}</span>'?</h5>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" name="artist_name" class="btn btn-danger mt-2">Delete</button>
            </form>
        </div>
    </section>

{% endblock main %}

templates/normal/music_list.html
{% extends 'normal/basepage.html' %}
{% load static %}
{% block title %}
    Music List
{% endblock title %}

{% block main %}

    <section>
        <h4 class="text-center m-3">Singer {{artist.name}} songs list
        <a href="{% url 'artistapp:a_music_add' artist.id %}" class="btn btn-info float-right btn-sm">Add New Song</a></h4>
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">S.N.</th>
                <th scope="col" >Song's Name</th>
                <th scope="col">Album</th>
                <th scope="col">Genre</th>
                <th scope="col">Created</th>
                <th scope="col">Updated</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for music in music_lists %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ music.title|truncatechars:25 }}</td>
                  <td>{{ music.album_name|default_if_none:'--' }}</td>
                  <td>{{ music.genre|default_if_none:'--' }}</td>
                  <td>{{ music.created_at|date:'d M Y'}}</td>
                  <td>{{ music.updated_at|date:'d M Y' }}</td>
                  <td>
                    <a href="{% url 'artistapp:a_music_update' music.id %}" class="btn btn-info btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <a href="{% url 'artistapp:a_music_delete' music.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></a>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="7">No songs</td>
                </tr>
                
              {% endfor %}
            </tbody>
          </table>
          <nav aria-label="...">
            <ul class="pagination">
              {% if artist_lists.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{artist_lists.previous_page_number}}" tabindex="-1">Previous</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="" tabindex="-1">Previous</a>
              </li>
              {% endif %}

              {% for page in totalpagelist %}
              {% if page == current_page %}
              <li class="page-item active">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              {% endfor %}
              {% if artist_lists.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{artist_lists.next_page_number}}" >Next</a>
              </li>
                {% else %}
              <li class="page-item disabled">
                <a class="page-link " href="">Next</a>
              </li>
                {% endif %}

            </ul>
          </nav>
    </section>

{% endblock main %}

templates/normal/user_list.html
{% extends 'normal/basepage.html' %}
{% load static %}
{% block title %}
    User List
{% endblock title %}

{% block main %}


    <section>
        <h4 class="text-center m-3">User Lists
        <a href="{% url 'artistapp:a_user_add' %}" class="btn btn-info float-right btn-sm">Add New User</a></h4>
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">S.N.</th>
                <th scope="col" >Email</th>
                <th scope="col">User Name</th>
                <th scope="col">Phone</th>
                <th scope="col">D.O.B.</th>
                <th scope="col">Gender</th>
                <th scope="col">Address</th>
                <th scope="col">Created</th>
                <th scope="col">Updated</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for user in user_lists %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ user.email }}</td>
                  <td>{{ user.first_name|truncatechars:40|default_if_none:'--' }} {{ user.last_name|truncatechars:40 }}</td>
                  <td>{{ user.phone|default_if_none:'--' }}</td>
                  <td>{{ user.dob|date:'d M Y'|default_if_none:'--' }}</td>
                  <td>{% if user.gender == 'm' %} Male{% elif user.gender == 'f' %} Female {% else %} Others{% endif %}</td>
                  <td>{{ user.address|default_if_none:'--' }}</td>
                  <td>{{ user.created_at|date:'d M Y'}}</td>
                  <td>{{ user.updated_at|date:'d M Y' }}</td>
                  <td>
                    <a href="{% url 'artistapp:a_user_update' user.id %}" class="btn btn-info btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <a href="{% url 'artistapp:a_user_delete' user.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          <nav aria-label="...">
            <ul class="pagination">
              {% if artist_lists.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{artist_lists.previous_page_number}}" tabindex="-1">Previous</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="" tabindex="-1">Previous</a>
              </li>
              {% endif %}

              {% for page in totalpagelist %}
              {% if page == current_page %}
              <li class="page-item active">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              {% endfor %}
              {% if artist_lists.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{artist_lists.next_page_number}}" >Next</a>
              </li>
                {% else %}
              <li class="page-item disabled">
                <a class="page-link " href="">Next</a>
              </li>
                {% endif %}

            </ul>
          </nav>
    </section>

{% endblock main %}