amsapp/urls.py
from django.urls import path,include
from .views import *

app_name = 'amsapp'

urlpatterns = [
    path('',ArtistListView.as_view(),name="artist_list"),
    path('artists/add/',ArtistAddView.as_view(),name="artist_add"),
    path('artist/<int:id>/update/',ArtistUpdateView.as_view(),name="artist_update"),
    path('artist/<int:id>/delete/',ArtistDeleteView.as_view(),name="artist_delete"),

    path('musics/<int:id>/',MusicListView.as_view(),name="music_list"),
    path('musics/add/<int:id>/',MusicAddView.as_view(),name="music_add"),
    path('music/<int:id>/update/',MusicUpdateView.as_view(),name="music_update"),
    path('music/<int:id>/delete/',MusicDeleteView.as_view(),name="music_delete"),   

    path('users/',UserListView.as_view(),name="user_list"),
    path('users/add/',UserAddView.as_view(),name="user_add"),
    path('user/<int:id>/update/',UserUpdateView.as_view(),name="user_update"),
    path('user/<int:id>/delete/',UserDeleteView.as_view(),name="user_delete"),   

    path('login/',ArtistLoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),

    path('export/',ArtitsFileExportView.as_view(),name="export"),
    path('import/',ArtitsFileImportView.as_view(),name="import"),

    
    
]

api/urls.py
from django.urls import path
from .views import *

urlpatterns =[
    path("login/", LoginAPIView.as_view(), name="loginapi"),
    path('get-access/<int:id>/',GetAccessAPIView.as_view(), name="get_access"),

    path('artist/post/',ArtistPostAPIView.as_view(),name="artist_post"),
    path('artist/<int:id>/update/',ArtistUpdateAPIView.as_view(),name="artist_update"),
    path('artist/<int:id>/delete/',ArtistDeleteAPIView.as_view(),name="artist_delete"),
    path('artists/',ArtistListAPIView.as_view(),name="artist_list"),

    path('music/post/',MusicPostAPIView.as_view(),name="music_post"),
    path('music/<int:id>/update/',MusicUpdateAPIView.as_view(),name="music_update"),
    path('music/<int:id>/delete/',MusicDeleteAPIView.as_view(),name="music_delete"),
    path('musics/<int:id>/',MusicListAPIView.as_view(),name="music_list"),

    path('user/post/',UserPostAPIView.as_view(),name="user_post"),
    path('user/<int:id>/update/',UserUpdateAPIView.as_view(),name="user_update"),
    path('user/<int:id>/delete/',UserDeleteAPIView.as_view(),name="user_delete"),
    path('users/',UserListAPIView.as_view(),name="user_list"),

    path('artist-exp/',CSVExportArtistAPIView.as_view(), name="artist_export"),
    path('artist-imp/',CSVImportArtistAPIView.as_view(), name="artist_import"),

]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('amsapp.urls')),
    path("api/",include('api.urls')),
    path("frontend/",include('artistapp.urls')),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/user/user_delete.html
{% extends '../basepage.html' %}
{% load static %}
{% block title %}
    User delete
{% endblock title %}

{% block main %}


    <section>
        <div class="border border-secondary rounded p-3 mt-5"
            <h5 class="text-center m-3 text-danger">Are you sure, you want delete the user '<span class="text-info">{{obj.first_name}} {{obj.last_name}}</span>'?</h5>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" name="user_name" class="btn btn-danger mt-2">Delete</button>
            </form>
        </div>
    </section>

{% endblock main %}

templates/user/user_list.html
{% extends '../basepage.html' %}
{% load static %}
{% block title %}
    User List
{% endblock title %}

{% block main %}


    <section>
        <h4 class="text-center m-3">User Lists
        <a href="{% url 'amsapp:user_add' %}" class="btn btn-info float-right btn-sm">Add New User</a></h4>
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">S.N.</th>
                <th scope="col">User Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">D.O.B</th>
                <th scope="col">Gender</th>
                <th scope="col">Address</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ user.first_name|truncatechars:30 }} {{ user.last_name|truncatechars:30 }}</td>
                  <td>{{ user.email }}</td>
                  <td>{{ user.phone|default_if_none:'--' }}</td>
                  <td>{{ user.dob|default_if_none:'--' }}</td>
                  <td>{{ user.gender|default_if_none:'--'  }}</td>
                  <td>{{ user.address|default_if_none:'--'  }}</td>
                  <td>
                    <a href="{% url 'amsapp:user_update' user.id %}" class="btn btn-info btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <a href="{% url 'amsapp:user_delete' user.id %}" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></a>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="6">
                    No songs
                  </td>
                </tr>
                
                {% endfor %}
            </tbody>
          </table>
          {% if pages %}
          <nav aria-label="...">
            <ul class="pagination">
              {% if previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{previous}}" tabindex="-1">Previous</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="" tabindex="-1">Previous</a>
              </li>
              {% endif %}

              {% for page in pages %}
              {% if page == current_page %}
              <li class="page-item active">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              {% endfor %}
              {% if next_page %}
              <li class="page-item">
                <a class="page-link" href="?page={{next_page}}" >Next </a>
              </li>
                {% else %}
              <li class="page-item disabled">
                <a class="page-link " href="">Next</a>
              </li>
                {% endif %}

            </ul>
          </nav>
          {% endif %}
    </section>

{% endblock main %}

templates/user/user_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>API User Registration | Artist Management System</title>
</head>
<body>
    
    <div class="container">
    <main>
        <div class="account-pages my-5 pt-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12 col-lg-10 col-xl-8">
                        <div class="card overflow-hidden">
                            <div class="bg-soft-primary">
                                <div class="row  bg-secondary">
                                    <div class="col-12">
                                        <div class="text-primary p-4">
                                            <h5 class="text-white">ARTIST MAMAGEMENT SYSTEM</h5>
                                            <p class="text-white">User Registration</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body pt-0"> 
                               
                                <div class="p-2">
                                    <form method="POST" class="p-3">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="formGroupExampleInput">Email</label>
                                            {{forms.email}}
                                            {{forms.email.errors}}
                                          </div>    
                                          <div class="form-group">
                                            <label for="formGroupExampleInput">Password</label>
                                            {{forms.password}}
                                            {{forms.password.errors}}
                                          </div>        
                                          <div class="form-group">
                                            <label for="formGroupExampleInput">First name</label>
                                            {{forms.first_name}}
                                            {{forms.first_name.errors}}
                                          </div>            
                                          <div class="form-group">
                                            <label for="formGroupExampleInput">Last name</label>
                                            {{forms.last_name}}
                                            {{forms.last_name.errors}}
                                          </div>
                                          <div class="form-group">
                                            <label for="formGroupExampleInput">Phone</label>
                                            {{forms.phone}}
                                            {{forms.phone.errors}}
                                          </div>
                                        <div class="form-group">
                                          <label for="formGroupExampleInput2">D.O.B.</label>
                                          {{forms.dob}}
                                          {{forms.dob.errors}}
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput2">Gender</label>
                                            {{forms.gender}}
                                            {{forms.gender.errors}}
                                            
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput2">Address</label>
                                            {{forms.address}}
                                            {{forms.address.errors}}
                                        </div>
                                        <div class="mt-3">
                                            <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">Register</button>
                                        </div>
                                    </form>
                                </div>
            
                            </div>
                        </div>
                        <div class="mt-5 text-center">
                            
                            <div>
                                <p>© <script>document.write(new Date().getFullYear())</script> Artist Management System, by Pravin Rai</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
          </main>
    </div>
   
`   <script src="{% static 'js/bootstrap.min.js' %}">
    
</script>
</body>
</html>

templates/user/user_update.html
{% extends '../basepage.html' %}
{% load static %}
{% block title %}
    User Update Form
{% endblock title %}

{% block main %}
<section>
  <h4 class="text-center m-3">User Update Form</h4>
  <form method="POST" class="border rounded border-secondary p-3">
      {% csrf_token %}
      <div class="form-group">
        <div class="form-group">
          <label for="formGroupExampleInput">First name</label>
          {{forms.first_name}}
          {{forms.first_name.errors}}
        </div>            
        <div class="form-group">
          <label for="formGroupExampleInput">Last name</label>
          {{forms.last_name}}
          {{forms.last_name.errors}}
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput">Phone</label>
          {{forms.phone}}
          {{forms.phone.errors}}
        </div>
      <div class="form-group">
        <label for="formGroupExampleInput2">D.O.B.</label>
        {{forms.dob}}
        {{forms.dob.errors}}
      </div>
      <div class="form-group">
          <label for="formGroupExampleInput2">Gender</label>
          {{forms.gender}}
          {{forms.gender.errors}}
          
      </div>
      <div class="form-group">
          <label for="formGroupExampleInput2">Address</label>
          {{forms.address}}
          {{forms.address.errors}}
      </div>
      
      <button type="submit" name="user_btn" class="form-control btn-primary">Update</button>

    </form>
</section>


{% endblock main %}